services:
  bot:
    image: tg_bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - localhost
    environment:
      - SERVER_PORT = 8181
      - DB_URL = postgresql://postgres:xm6idbip@localhost/bot

  localhost:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xm6idbip
    ports:
      - "15432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: buschkow2005@gmail.com
      PGADMIN_DEFAULT_PASSWORD: xm6idbip
    ports:
      - "5050:80"
